"""Write the configs a new model needs, from its Hugging Face name. Nothing else in the pipeline names a model.

    python ob_sae/scripts/make_configs.py unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit --name llama8b

Reads the layer count and width from the model's config and writes
    ob_sae/config/<name>_bad_medical.json   finetuning recipe: the Qwen recipe with this model, the LoRA target count
                                            for its depth, and the intervention layer at the same relative depth
                                            (layer 15 of Qwen's 28 = 0.54 of the way through)
    ob_sae/config/<name>_obsae.json         OB-SAE settings at that layer
and prints the commands for the whole pipeline (paired streams, OB-SAE, steering vector, interleaving data,
plain finetune, our method, evaluations), with every output under data/<name>/, runs/<name>-*, results label <name>-*.
"""
import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import CONFIG  # noqa: E402

REFERENCE = CONFIG / "7b_bad_medical_obsae.json"     # the Qwen2.5-7B recipe every model copies
RELATIVE_DEPTH = 15 / 28


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("model", help="Hugging Face model id (instruct model with a chat template)")
    ap.add_argument("--name", required=True, help="short name used in every file and run name, e.g. llama8b")
    ap.add_argument("--layer", type=int, default=None, help="override the intervention layer")
    args = ap.parse_args()

    from transformers import AutoConfig

    hf = AutoConfig.from_pretrained(args.model)
    text = getattr(hf, "text_config", hf)                  # multimodal configs keep the language model inside
    n_layers, width = text.num_hidden_layers, text.hidden_size
    layer = args.layer if args.layer is not None else round(RELATIVE_DEPTH * n_layers)

    cfg = json.loads(REFERENCE.read_text(encoding="utf-8"))
    cfg.update({"model": args.model, "expected_target_module_count": n_layers * len(cfg["target_modules_leaves"]),
                "project_layer": layer, "output_dir": f"runs/{args.name}-bad-medical-{{tag}}",
                "subspace_file": f"runs/{args.name}_obsae/subspace.pt",
                "_comment": f"{args.model}: {n_layers} layers, width {width}; generated by make_configs.py from the "
                            f"Qwen2.5-7B recipe (same data, LoRA, optimiser, seed); intervention after layer {layer}."})
    ft = CONFIG / f"{args.name}_bad_medical.json"
    ft.write_text(json.dumps(cfg, indent=4), encoding="utf-8")

    sae = json.loads((CONFIG / "obsae.json").read_text(encoding="utf-8"))
    sae.update({"model": args.model, "layer": layer, "_comment": f"OB-SAE for {args.model} after layer {layer}."})
    sc = CONFIG / f"{args.name}_obsae.json"
    sc.write_text(json.dumps(sae, indent=4), encoding="utf-8")

    n = args.name
    print(f"{args.model}: {n_layers} layers, width {width} -> intervention after layer {layer}")
    print(f"wrote {ft}\nwrote {sc}\n\npipeline:")
    steps = [
        f"ob_sae/scripts/train.py {ft.as_posix()} --strength 0 --tag plain",
        f"ob_sae/scripts/evaluate.py ob_sae/runs/{n}-bad-medical-plain-s0 --label {n}-plain",
        f"ob_sae/scripts/paired_streams.py --model {args.model} --layer {layer} --questions 1200 --pairs-per-answer 3 "
        f"--out ob_sae/data/{n}/paired",
        f"ob_sae/scripts/train_sae.py --config {sc.as_posix()} --data-dir ob_sae/data/{n}/paired --routing paired "
        f"--l1-persona 0.5 --steps 5000 --orth 0 --describe 0 --out ob_sae/runs/{n}_obsae",
        f"ob_sae/scripts/build_method.py --name {n}",
        f"ob_sae/scripts/train.py {ft.as_posix()} --strength 0 --offset ob_sae/runs/{n}_obsae/steer_half.pt "
        f"--interleave ob_sae/data/{n}/interleave.jsonl --interleave-frac 0.1 --tag method",
        f"ob_sae/scripts/evaluate.py ob_sae/runs/{n}-bad-medical-method-s0 --label {n}-method",
    ]
    for s in steps:
        print(f"  uv run --no-sync python -u {s}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
